Решено. Тесты проходят.
js-tasks-ru/jsbasic-20210420_shambazov pull request #2
Opened 2021-04-24 18:02 UTC by slv177

Вопрос - почему в 4 задании не срабатывал перебор по словарю? Спотыкался на 'xxx'.
Мне кажется, лучше слова-признаки вынести в отдельный словарь, чтоб потом легко можно было изменить их список.

2021-04-24 18:02 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-04-25 11:22 UTC, SinimaWath requested changes

2021-04-25 11:22 UTC, SinimaWath commented on 1-module/4-task/index.js
> +//   const badWords = ['xxx', '1xbet'];
Вынести в словарь - очень хорошее решение. Давай его добьем:
- Этот словарь лучше вынести в отдельную конфиг переменную, в глобальную область: `const BAD_WORDS = [....]`. Чтобы на каждый вызов функции не инициализировать массив.
- Для обхода массива нужно использовть for of, for in - это немного другое

2021-04-25 11:22 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    return str.slice(0, maxlength - 1) + "…";
Давай используем шаблонные строки

2021-04-26 16:14 UTC, SinimaWath approved these changes

2021-04-26 16:15 UTC, merged